### ISSUE TITLE
All encoded results end with `%0A` (newline)

### ISSUE THREAD

**Issue by ShredderWalnut** [derhuerst/url-decode-encode-cli#2]
When I use `url-decode-encode-cli` to encode text, all the results end with an encoded newline, `%0A`. To make sure I wasn't doing anything wrong, I copied the example from the website,
```bash
echo '{"foo": "bar"}' | url-encode
```
and the result was
```bash
%7B%22foo%22%3A%20%22bar%22%7D%0A%
```
I'm using macOS Big Sur version 11.0 Beta (20A5374g).

**Comment by derhuerst** [comment]
This is because by default `echo` adds a newline at the end. In the bash and fish shells (don't know about the others), you can use `echo -n` to avoid this.
